[gdrive]
type = "service_account"
project_id = "aplikasi-pelaporan-461003"
private_key_id = "42e9d00e591b35049a6f6196802b47a1a67ee782"
private_key = "-----BEGIN PRIVATE KEY-----\nMIIEvAIBADANBgkqhkiG9w0BAQEFAASCBKYwggSiAgEAAoIBAQCoL6lvE4lotCDugOotzo3FrZoomVNfaTCEN4Bm6lFXcvFwwUjlHAQd5mNs+zyXUr3siZJdqcLvedQj...potongan...\nzMc2jEviIwKBgHC6uth7SRV2ZjiQdP/VSJwnf92oZaUAxAs7yHRrX9dInbKjyTaH\n-----END PRIVATE KEY-----"
client_email = "streamlit-drive-access@aplikasi-pelaporan-461003.iam.gserviceaccount.com"
client_id = "101276274047408629684"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/streamlit-drive-access%40aplikasi-pelaporan-461003.iam.gserviceaccount.com"
folder_id = "1FmHd1sA3THdzePvUVCl1NX3LPyNj5MVv"
